### PR TITLE
Swear words.

### PR DESCRIPTION
**Pull request by virtadpt**
Added a large portion of dariusk's wordfilter list
(https://github.com/dariusk/wordfilter/blob/master/lib/badwords.json)
to english/swear_words.csv.

Signed-off-by: The Doctor <drwho@virtadpt.net>

### CODE REVIEW

**Comment by gunthercox** [comment]
@Issen007 Be mindful of software licenses when merging in changes that originate from another project.

The wordfilter project is [released under the MIT license](https://github.com/dariusk/wordfilter/blob/master/LICENSE-MIT) which is a permissive license but still requires:

> Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

> The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

These changes included just a few words and I _believe_ no further changes are necessary. However I just wanted to make it clear that licencing is important and needs to be appropriately respected.

**Comment by virtadpt** [comment]
I saw that and read through it.  I reconsidered filing this PR a couple of times due to the license.  I also did not expect it to be accepted due to its subject matter (i.e., vulgarity).

**Comment by gunthercox** [comment]
@virtadpt If you want to make a PR that removes the swear words files all together that would be appreciated too. These files were originally added so that they might be able to be used for https://github.com/gunthercox/ChatterBot/pull/278

**Comment by virtadpt** [comment]
That might be the thing to do.  In my code, I import the `wordfilter` module and do the profanity filtering in my code, and not at the corpus level.  c.f. https://github.com/virtadpt/exocortex-halo/blob/master/beta_fork/clients/irc-bot.py#L634

**Comment by Issen007** [comment]
@gunthercox sorry for that, didn't know that. But sow that is has been fixed.

**Pull request merged**
