### PR TITLE
Modifications to the english/ai.yml file.

### PR DESCRIPTION
**Pull request by virtadpt**
I had a little fun in the english/ai.yml file, added some new responses and a couple of new questions.

### CODE REVIEW

**Comment by Issen007** [comment]
@virtadpt that's ok, please merge it.
For next time, please merge and do a new PR next time. It is much easier for us to keep track of all changes.

**Comment by vkosuri** [comment]
@Issen007 I am not sure @virtadpt has merge capabilities, I don't have any issue with PR, LGTM 👍

**Comment by Issen007** [comment]
@vkosuri you are maybe right, maybe I was little bit unlucky when I thought. ;)

@virtadpt can you Merge it or does it wait for us to do that?

**Comment by virtadpt** [comment]
@Issen007 I do not have merge privileges on this repository.  All I can do is file PR's.

I thought the first file modification had already been merged, hence my confusion.

**Pull request merged**
