### PR TITLE
Tried fixing drugs.yml again.

### PR DESCRIPTION
**Pull request by virtadpt**
Okay.  I've done some tinkering on my local copy of the drugs-fixed/ branch, and I think this is a cleaner merge.  Could you take a look at it, and if it's still bad I might need some help fixing it (because Git claims everything's fine on my end and there is no conflict, even after a `git fetch upstream`).

### CODE REVIEW

**Comment by vkosuri** [comment]
@virtadpt This branch has conflicts that must be resolved

**Comment by gunthercox** [comment]
I've noticed that even after you push up a merge commit (I recommend doing a rebase instead of this month) your branch is still out of date. This leads me to believe that the master branch on your fork of this repository is out of date with the master branch of the main repository. You should be able to check this by verifying if the latest commit on the master branch of each repository is the same.

I'll be more than happy to help you further as soon as we figure out why in the pull quests are continuously out of date.

**Comment by gunthercox** [comment]
@virtadpt I'm going to close this ticket off. The `drugs.yml` file was removed some time ago.

**Comment by virtadpt** [comment]
Acknowledged.

**Pull request closed without merging**
