### PR TITLE
intial readme

### PR DESCRIPTION
**Pull request by vkosuri**

### CODE REVIEW

**Comment by vkosuri** [comment]
@gunthercox could you please make master as default branch, accidentally the corpus branch as acting as master.

**Comment by gunthercox** [comment]
Sure, the change has been made.

**Comment by vkosuri** [comment]
@gunthercox Thanks, I am closing this.

1. Adding chatterbot corpus tests to this repository?
2. Moving all the stuff related chatterbot corpus and delete to this do you think is it right way?

**Comment by gunthercox** [comment]
Addressing your questions in order:

1. This would probably be a good idea. Adding tests helps catch invalid data that can possibly get submitted in pull requests and it helps to ensure that ChatterBot will read the data files.
2. As long as it remains easy to train a small chat bot example I am fine with the corpus data being moved to this repository entirely.

**Comment by vkosuri** [comment]
@gunthercox Thanks master.

I am going to submit another PR with tests ASAP

**Pull request closed without merging**
