### PR TITLE
Conversations fixed

### PR DESCRIPTION
**Pull request by virtadpt**
Fixed up things in conversations.yml that I broke because I didn't understand the internal format.

### CODE REVIEW

**Comment by vkosuri** [comment]
@virtadpt Again this branch has conflicts, could you look into

**Comment by virtadpt** [comment]
Will-do.  I'll get to it after work today.

**Comment by gunthercox** [comment]
Hi @virtadpt I was able to manually rebase some of the other pull requests but this one has too many conflicts for me to resolve in a reasonable amount of time. I'd still be happy to accept contributions, but I'd like to just be able to click the merge button :sweat_smile:

I'm going to close #87 and #82 off for similar reasons. Again, feel free to resubmit if you are still interested in contributing those changes.

**Comment by virtadpt** [comment]
Hi.  I'm dealing with family stuff (PM me for details, if you like) right now, so I'm not going to have time until the holidays.  Feel free to delete these PRs and I'll fix them up on my end when things calm down in late November or early December.

**Pull request closed without merging**
