### PR TITLE
Change format of corups files from json to yml

### PR DESCRIPTION
**Pull request by gunthercox**
This change is intended to help improve readability and enforce proper formatting in the corpus data files.

### CODE REVIEW

**Comment by vkosuri** [comment]
@gunthercox Master is there any backward compatible? For example can i use json corpus files instead of YAML files?

**Comment by gunthercox** [comment]
@vkosuri Yes, json is a subset of yaml so if json formatted content is placed in a `.yml` file it can still be read.

**Comment by vkosuri** [comment]
one more question, currently we are reading statement and response from a JSON list, the same process will apply here also?

For example

```YAML
greetings:
  'statement-1',
  'response-1',
  'statement-n'
  'response-n'
```

**Comment by gunthercox** [comment]
The process is still very much the same. The following two blocks are equivalent:

```json
{
  "greetings": [
    [
      "statement-1",
      "response-1",
      "statement-n",
      "response-n"
    ]
  ]
}
```

```yaml
greetings:
- - statement-1
  - response-1
  - statement-n
  - response-n
```

https://www.json2yaml.com/ is also a fairly good tool for exploring these difference.

**Pull request merged**
