### PR TITLE
Add missing '-' for conversations.yml

### PR DESCRIPTION
**Pull request by kelvinau**

### CODE REVIEW

**Comment by kelvinau** [comment]
```
- What languages do you like to use?
  - I use Python, Java and C++ quite often.
  - I use Python quite a bit myself.
  - I'm not incredibly fond of Java.
```
`pyyaml` thinks that it is just a normal value instead of a key, so it reads it as
 `- What languages do you like to use? - I use Python, Java and C++ quite often. - I use Python quite a bit myself. - I'm not incredibly fond of Java.`
, which is just a concatenated string with '-' and space in it. This is a correct yaml format.
If we really want to prevent this, we will also need to explicitly check the spacing of the key & value.

**Comment by vkosuri** [comment]
@kelvinau Thank you very much, 

> If we really want to prevent this, we will also need to explicitly check the spacing of the key & value.

could you add some tests to prevent this issue/bug/etc?

**Comment by kelvinau** [comment]
Sure. I can add some tests for this. I think we can merge this PR first?

**Comment by vkosuri** [comment]
Before merging this PR, I am looking comments/suggestion from @gunthercox also

**Pull request merged**
