### PR TITLE
Update for japanese data

### PR DESCRIPTION
**Pull request by tt-anh-eole**

### CODE REVIEW

**Comment by gunthercox** [comment]
@tt-anh-eole Thank you.

**Comment by tt-anh-eole** [comment]
Execute me, when i reinstall chatter_corpus, i still not have japanese data in chatterbot_corpus_data, can you show me the reason? Thanks you so much

**Comment by gunthercox** [comment]
What command are you using to do the install?

**Comment by tt-anh-eole** [comment]
I just install chatterbot again because i think in **chatterbot/requirements.txt** file, you have wrote **chatterbot-corpus**

**Comment by tt-anh-eole** [comment]
When i use command **pip install chatterbot-corpus**, It still not have japanese/ folder

**Comment by gunthercox** [comment]
When installing using the `requirements.txt` file, the latest version of the chatterbot-corpus module is installed from PyPI (https://pypi.org/project/chatterbot-corpus/). Your contributions from this pull request are currently only on GitHub because the updated content is not automatically uploaded to PyPi.

`pip` supports installing from GitHub

```
python3 -m pip install git+git://github.com/gunthercox/chatterbot-corpus.git@master
```

**Comment by tt-anh-eole** [comment]
When i deploy to heroku, i wrote in my requirements.txt file is:
**chatterbot==0.8.7
git+git://github.com/gunthercox/chatterbot-corpus.git@master**

And after deploy I receive this log:

**Comment by gunthercox** [comment]
ChatterBot version 0.8.7 is not compatible with the latest version of chatterbot-corpus on the `master` branch. As a temporary solution, you could include the training files in your Heroku deployment and use a file path to specify the training data source. For example:

```python
chatterbot.train('./data/my_corpus/')
```

**Comment by tt-anh-eole** [comment]
Thanks you so much for supporting me, it row running

**Pull request merged**
